shortcut:
  auto_save: X
  change_output_dir: Shift+Z
  clear: Ctrl+Shift+Z
  clear_label_list: ''
  clear_recent: ''
  close: Ctrl+W
  convert_mask: ''
  data_widget: ''
  del_active_polygon: Backspace
  del_all_polygon: ''
  det_widget: ''
  edit_shortcuts: E
  enterEISegMed3D: ''
  export_label_list: ''
  finish_object: Space
  grid_ann_widget: ''
  import_label_list: ''
  label_widget: ''
  largest_component: ''
  load_param: Ctrl+M
  mi_widget: ''
  model_widget: ''
  open_folder: Shift+A
  open_image: Ctrl+A
  origional_extension: ''
  quick_start: ''
  quit: ''
  redo: Ctrl+Y
  report_bug: ''
  rs_widget: ''
  save: ''
  save_as: ''
  save_coco: ''
  save_cutout: ''
  save_grayscale: ''
  save_json: ''
  save_pseudo: ''
  save_yolo: ''
  segmentation_widget: ''
  set_cross_color: ''
  set_cutout_background: ''
  td_widget: ''
  toggle_logging: ''
  turn_next: F
  turn_prev: S
  typing_det: ''
  typing_seg: ''
  undo: Ctrl+Z
  use_qt_widget: ''
  video_anno_widget: ''
  video_play_widget: ''
